[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/"
]

[start]
cmd = "node backend/server.js"